config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', to: 'pages#home'
  get 'complete', to: 'pages#complete'
  get 'feedback', to: 'pages#feedback'
  # get 'goalset', to: 'pages#goalset'
  get 'progress', to: 'pages#progress'
  get 'signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/goalset', to: 'goals#new'
  post '/goals', to: 'goals#create'

  resources :goals, only: [:edit, :update, :destroy]
  resources :feedbacks, only: [:create]

  get '/goalindex', to: 'goals#index', as: 'goalindex'
  get '/feedbackindex', to: 'feedbacks#index', as: 'feedbackindex'
  get '/feedbackshow', to: 'feedbacks#show', as: 'feedbackshow'

  resources :mid_term_goals do
    resources :feedbacks, only: [:index, :new, :create, :show]
  end

  resources :users 
  # only: [:show, :create]  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  belongs_to :mid_term_goal, optional: true

  validates :content, presence: true
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_goal

    def index
      @long_term_goals = current_user.long_term_goals
      @mid_term_goals = current_user.mid_term_goals
    end

    def edit
    end

    def show
      @long_term_goals = current_user.long_term_goals
      @mid_term_goals = current_user.mid_term_goals
      @feedbacks = current_user.feedbacks
    end

    def new
      @feedback = @goal.feedbacks.build
    end

    def update
      if @goal.update(feedback_params)
        redirect_to feedbackindex_path, notice: 'フィードバックが入力されました'
      end
    end

    def create
      @feedback = @goal.feedbacks.build(feedback_params)
      @feedback.user = current_user
  
      if @feedback.save
        update_mid_goal_complete
        redirect_to feedbackindex_path, notice: 'フィードバックが正常に作成されました。'
      else
        render :new
      end
    end
  
    private
  
    def set_goal
      params[:mid_term_goal_id]
      @goal = MidTermGoal.find_by(id: params[:mid_term_goal_id])
    end
  
    def feedback_params
      params.require(:feedback).permit(:content)
    end

    def update_mid_goal_complete
      if @goal.is_a?(MidTermGoal)
        @goal.update(is_complete: true)
      end
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>目標確認ページ</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <div class="container mt-5">
    <h1 class="row justify-content-center">フィードバックを入力する目標を選択してください。</h1>
    <div class="mb-5">
      <h3>中期的な目標</h3>
      <ul class="list-group">
        <% incomplete_goals = @mid_term_goals.select { |goal| !goal.is_complete } %>
        <% if incomplete_goals.any? %>
          <% incomplete_goals.each do |goal| %>
            <li class="list-group-item">
              <strong>中期的な目標:</strong><%= goal.mid_goal %><br>
              <strong>何をするのか:</strong><%= goal.what_to_do %><br>
              <strong>なぜそれを行うのか:</strong><%= goal.why_to_do %><br>
              <strong>なぜ現状がそうなっているのか:</strong><%= goal.why_current_status %><br>
              <strong>優先順位:</strong><%= goal.priority %><br>
              <strong>締め切り:</strong><%= goal.mid_goal_deadline.strftime("%Y/%m/%d") %><br>
              <strong>目標作成した日:</strong><%= goal.created_at.strftime("%Y/%m/%d") %><br>
              <%= link_to 'フィードバックを入力する', new_mid_term_goal_feedback_path(goal) %>
            </li>
          <% end %>
      </ul>
        <% else %>
          <p>目標が見つかりませんでした。</p>
        <% end %>
    </div>
  </div>
</body>


app/views/feedbacks/new.html.erb
<%= form_with(model: [@goal, @feedback], local: true) do |form| %>
  <h2 class="row justify-content-center">フィードバック入力ページ</h2>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form.label :content, '選択した目標のフィードバックを入力してください。', class: "form-label bold-label" %>
      <%= form.text_field :content, class: "form-control" %>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-auto">
      <%= form.submit '登録', class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/feedbacks/show.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>目標確認ページ</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
<div class="container mt-5">
  <h1 class="row justify-content-center">過去に達成した目標</h1>
  <div class="mb-5">
    <% complete_goals = @mid_term_goals.select { |goal| goal.is_complete } %>
    <% if complete_goals.any? %>
      <ul class="list-group">
        <% complete_goals.each do |goal| %>
          <li class="list-group-item">
            <strong>中期的な目標:</strong> <%= goal.mid_goal %><br>
            <strong>何をするのか:</strong> <%= goal.what_to_do %><br>
            <strong>なぜそれを行うのか:</strong> <%= goal.why_to_do %><br>
            <strong>なぜ現状がそうなっているのか:</strong> <%= goal.why_current_status %><br>
            <strong>優先順位:</strong> <%= goal.priority %><br>
            <strong>締め切り:</strong> <%= goal.mid_goal_deadline.strftime("%Y/%m/%d") %><br>
            <strong>目標作成した日:</strong> <%= goal.created_at.strftime("%Y/%m/%d") %><br>
            <strong>自己フィードバック:</strong><br>
            <ul>
              <% goal.feedbacks.each do |feedback| %>
                <li><%= feedback.content %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
        <% else %>
          <p>達成された目標が見つかりませんでした。</p>
        <% end %>
  </div>
</div>
</body>