config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', to: 'pages#home'
  get 'complete', to: 'pages#complete'
  get 'feedback', to: 'pages#feedback'
  # get 'goalset', to: 'pages#goalset'
  get 'progress', to: 'pages#progress'
  get 'signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/goalset', to: 'goals#new'
  post '/goals', to: 'goals#create'

  resources :goals, only: [:edit, :update, :destroy]
  resources :feedbacks, only: [:create]

  get '/goalindex', to: 'goals#index', as: 'goalindex'
  get '/feedbackindex', to: 'feedbacks#index', as: 'feedbackindex'
  get '/feedbackshow', to: 'feedbacks#show', as: 'feedbackshow'

  resources :mid_term_goals do
    resources :feedbacks, only: [:index, :new, :create, :show]
  end

  resources :users 
  # only: [:show, :create]  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :authenticate_user! # ログインしていない場合アクセスを制限
    before_action :set_goal, only: [:edit, :update, :destroy]

    def index
      @long_term_goals = current_user.long_term_goals
      @mid_term_goals = current_user.mid_term_goals
    end

    def update
      if @goal.update(goal_params)
        redirect_to goalindex_path, notice: '目標が更新されました'
      else
        render :edit
      end
    end

    def edit
    end
  
    def show
    end

    def destroy
      @goal.destroy
      redirect_to goal_path, notice: '目標は削除されました。'
    end
  
    def new
      @long_term_goal = LongTermGoal.new
      @mid_term_goal = MidTermGoal.new
    end

    def create
      @long_term_goal = LongTermGoal.new(long_term_goal_params)
      @long_term_goal.user = current_user
      
      mid_term_goals = []

      # 受け取ったパラメータを処理
      (1..5).each do |i|
        if params[:goal]["mid_goal_#{i}"].present?
          mid_term_goal = MidTermGoal.new(
            mid_goal: params[:goal]["mid_goal_#{i}"],
            what_to_do: params[:goal]["what_to_do_#{i}"],
            why_to_do: params[:goal]["why_to_do_#{i}"],
            current_status: params[:goal]["current_status_#{i}"],
            why_current_status: params[:goal]["why_current_status_#{i}"],
            what_next: params[:goal]["what_next_#{i}"],
            mid_goal_deadline: params[:goal]["mid_goal_deadline_#{i}"],
            priority: params[:goal]["priority_#{i}"]
          )
          mid_term_goal.user = current_user
          mid_term_goal.long_term_goal = @long_term_goal
          mid_term_goals << mid_term_goal
        end
      end

      if logged_in?
        # トランザクションで保存
        ActiveRecord::Base.transaction do
          @long_term_goal.save!
          mid_term_goals.each(&:save!)
        end
        redirect_to goals_path, notice: '目標が作成されました。'
      else
        flash.now[:alert] = 'ログインしてください。'
        render :new, status: :unprocessable_entity
      end
    rescue ActiveRecord::RecordInvalid => e
      flash.now[:alert] = e.message
      render :new
    end

    private

    def set_goal
      @goal = if params[:type] == 'long_term'
        LongTermGoal.find(params[:id])
      else
        MidTermGoal.find(params[:id])
      end
    end

    def goal_params
      if params[:type] == 'long_term'
        params.require(:long_term_goal).permit(:long_goal, :long_goal_deadline)
      else
        params.require(:mid_term_goal).permit(:mid_goal, :what_to_do, :why_to_do, :current_status, :why_current_status, :what_next, :priority, :mid_goal_deadline)
      end
    end

    def long_term_goal_params
      params.require(:goal).permit(:long_goal, :long_goal_deadline)
    end

    def mid_term_goal_params(index)
      params.require(:goal).permit(
        "mid_goal_#{index}",
        "what_to_do_#{index}",
        "why_to_do_#{index}",
        "current_status_#{index}",
        "why_current_status_#{index}",
        "what_next_#{index}",
        "mid_goal_deadline_#{index}",
        "priority_#{index}"
      )
    end 
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/edit.html.erb
<%= form_with(model: @goal, local: true, url: goal_path(@goal, type: params[:type])) do |form| %>
  <% if @goal.is_a?(LongTermGoal) %>

  <h2 class="row justify-content-center">目標編集ページ</h2>
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="mb-3">
          <%= form.label :long_goal, '長期的な目標', class: "form-label bold-label" %>
          <%= form.text_field :long_goal, class: "form-control" %>
        <div>
      </div>

      <div class="mb-3">
        <%= form.label :long_goal_deadline, '締め切り', class: "form-label" %>
        <%= form.date_field :long_goal_deadline, class: "form-control" %>
      </div>
    </div>  

  <% else %>
    <h2 class="row justify-content-center">目標編集ページ</h2>
      <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="mb-3">
              <%= form.label :mid_goal, '中期的な目標', class: "form-label bold-label" %>
              <%= form.text_field :mid_goal, class: "form-control" %>
            </div>

          <div class="mb-3">
            <%= form.label :what_to_do, '何をするのか', class: "form-label" %>
            <%= form.text_field :what_to_do, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :why_to_do, 'なぜそれを行うのか', class: "form-label" %>
            <%= form.text_field :why_to_do, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :current_status, '現状どうなのか', class: "form-label" %>
            <%= form.text_field :current_status, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :why_current_status, 'なぜ現状そうなっているのか', class: "form-label" %>
            <%= form.text_field :why_current_status, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :what_next, 'では何をするのか', class: "form-label" %>
            <%= form.text_field :what_next, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :mid_goal_deadline, '締め切り', class: "form-label" %>
            <%= form.number_field :priority, class: "form-control" %>
          </div>

          <div class="field">
            <%= form.label :deadline %>
            <%= form.date_field :mid_goal_deadline, class: "form-control" %>
          </div>
        </div>
      </div>
    <% end %>

  <div class="row justify-content-center mb-3">
    <div class="col-auto mt-5">
      <div class="actions">
        <%= form.submit "目標を更新" %>
      </div>
    </div>
  </div>
<% end %>

<%= link_to 'Back', goalindex_path %>

app/views/goals/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>目標確認ページ</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="row justify-content-center">目標一覧ページ</h1>
        
        <div class="mb-5">
            <h3>長期的な目標一覧</h3>
            <% if @long_term_goals.present? %>
            <ul class="list-group">
                <% @long_term_goals.each do |goal| %>
                <li class="list-group-item">
                    <strong>長期的な目標:</strong> <%= goal.long_goal %><br>
                    <strong>締め切り:</strong> <%= goal.long_goal_deadline.strftime("%Y/%m/%d") %><br>
                    <strong>目標作成した日:</strong> <%= goal.created_at.strftime("%Y/%m/%d") %><br>
                    <%= link_to 'Edit', edit_goal_path(goal, type: 'long_term') %>
                    <%= link_to 'Delete', goal_path(goal, type: 'long_term'), data: { turbo_method: :delete } %>
                </li>
                <% end %>
            </ul>
            <% else %>
            <p>長期的な目標が見つかりませんでした。</p>
            <% end %>
        </div>
        
        <div>
            <h3>中期的な目標一覧</h3>
            <ul class="list-group">
                <% incomplete_goals = @mid_term_goals.select{ |goal| !goal.is_complete } %>
                <% if incomplete_goals.any? %>
                    <% incomplete_goals.each do |goal| %>
                        <li class="list-group-item">
                            <strong>中期的な目標:</strong> <%= goal.mid_goal %><br>
                            <strong>何をするのか:</strong> <%= goal.what_to_do %><br>
                            <strong>なぜそれを行うのか:</strong> <%= goal.why_to_do %><br>
                            <strong>現状どうなのか:</strong> <%= goal.current_status %><br>
                            <strong>なぜ現状そうなっているのか:</strong> <%= goal.why_current_status %><br>
                            <strong>では何をするのか:</strong> <%= goal.what_next %><br>
                            <strong>優先順位:</strong> <%= goal.priority %><br>
                            <strong>締め切り:</strong> <%= goal.mid_goal_deadline.try(:strftime, "%Y-%m-%d") || "締め切りが設定されていません" %><br>
                            <strong>目標を作成した日:</strong> <%= goal.created_at.strftime("%Y/%m/%d") %><br>
                            <%= link_to 'Edit', edit_goal_path(goal, type: 'mid_term') %>
                            <%= link_to 'Delete', goal_path(goal, type: 'mid_term'), data: { turbo_method: :delete } %>
                        </li>
                    <% end %>
            </ul>
                <% else %>
                    <p>中期的な目標が見つかりませんでした。</p>
                <% end %>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/goals/new.html.erb
<%= form_with url: goals_path, scope: :goal, local: true do |form| %>
  <h2 class="row justify-content-center">目標設定ページ</h2>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :long_goal, '長期的な目標', class: "form-label bold-label" %>
        <%= form.text_field :long_goal, class: "form-control" %>
      </div>
      <div class="mb-5">
        <%= form.label :long_goal_deadline, '締め切り', class: "form-label" %>
        <%= form.date_field :long_goal_deadline, class: "form-control" %>
      </div>
      
      <div id="mid-goals">
        <div class="mid-goal-field">
          <div class="mb-3">
            <%= form.label :mid_goal, '中期的な目標', class: "form-label bold-label" %>
            <%= form.text_field :mid_goal_1, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :what_to_do, '何をするのか', class: "form-label" %>
            <%= form.text_field :what_to_do_1, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :why_to_do, 'なぜそれを行うのか', class: "form-label" %>
            <%= form.text_field :why_to_do_1, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :current_status, '現状どうなのか', class: "form-label" %>
            <%= form.text_field :current_status_1, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :why_current_status, 'なぜ現状そうなっているのか', class: "form-label" %>
            <%= form.text_field :why_current_status_1, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :what_next, 'では何をするのか', class: "form-label" %>
            <%= form.text_field :what_next_1, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :mid_goal_deadline, '締め切り', class: "form-label" %>
            <%= form.date_field :mid_goal_deadline_1, class: "form-control" %>
          </div>
          <div class="mb-5">
            <%= form.label :priority, '優先順位', class: "form-label" %>
            <%= form.select :priority_1, options_for_select([['low', 1], ['medium', 2], ['high', 3]]), {}, { class: "form-control" } %>
          </div>
          <div class="row justify-content-center mb-3">
            <div class="col-auto">
              <button type="button" class="remove-mid-goal" style="display: none;">-</button>
            </div>
          </div>
        </div>
      </div>

      <div class="row justify-content-center mb-3">
        <div class="col-auto">
          <button type="button" id="add-mid-term-goals">+</button>
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-auto">
          <%= form.submit '登録', class: "btn btn-success" %>
        </div>
      </div>

    </div>
  </div>
<% end %>